version: '3.9'

services:
  mcp-server:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp123
      POSTGRES_DB: mcpdb
    ports:
      - "5432:5432"
